image:
  repository: gcr.io/flight-streaming-project/opensky-consumer
  tag: latest
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  create: false
  name: opensky-consumer-sa


env:
  - name: KAFKA_TOPIC
    value: "opensky"
  - name: KAFKA_BROKER
    value: "kafka.kafka.svc.cluster.local:9092"
  - name: KAFKA_USERNAME
    value: "user1"
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kafka-user-passwords
        key: client-passwords
  - name: BIGQUERY_PROJECT
    value: "flight-streaming-project"
  - name: BIGQUERY_DATASET
    value: "opensky_dataset" 
  - name: BIGQUERY_TABLE
    value: "flights"
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "/var/secrets/google/key.json"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"